name: Upload to GCS every Wednesday

on:
  push:
    branches: [ main ]
    paths:
      - '**.go'
  schedule:
    - cron: '5 20 * * WED'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'

      - name: "build and run"
        env:
          TWITCH_ID: ${{ secrets.TWITCH_ID }}
          TWITCH_SECRET: ${{ secrets.TWITCH_SECRET }}
          TWITCH_USERS: ${{ secrets.USERS }}
        run: |
          go install
          go run .


      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - id: "upload-folder"
        uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: "clips/"
          destination: "www.ohgustie.com/clips/"
          parent: false
